= RESTful Front Staging OAuth2 Client API Specification
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectnums:
:sectnumlevels: 2

{project-version}

== Login

=== User Login for Web Api

A `POST` request is used to login a new web user（Web 用户登录）

operation::web-login[snippets='http-request,request-headers,curl-request,http-response,response-fields']

=== User Login for Mobile Api

A `POST` request is used to login a new mobile user（移动端用户登录）

operation::mobile-login[snippets='http-request,request-headers,curl-request,http-response,response-fields']


== Refresh Token

=== Refresh Token for Web Api

A `POST` request is used to a new web refresh token （Web 用户刷新Token）

operation::web-refresh-token[snippets='http-request,request-headers,curl-request,http-response,response-fields']

=== Refresh Token for Mobile Api

A `POST` request is used to a new mobile refresh token (移动端用户刷新Token)

operation::mobile-refresh-token[snippets='http-request,request-headers,curl-request,http-response,response-fields']