= RESTful 后台 (Back Staging) OAuth2 客户端 API Specification
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectnums:
:sectnumlevels: 2

{project-name} : {project-version}

== 登录

=== Web端用户获取验证码

A `POST` request is used to get security code

operation::gen-security-code[snippets='http-request,curl-request,http-response,response-fields']


=== Web端用户登录

A `POST` request is used to login a new web user（Web 用户登录）

operation::web-login[snippets='http-request,request-headers,request-fields,curl-request,http-response,response-fields']

=== 移动端用户登录

A `POST` request is used to login a new mobile user（移动端用户登录）

operation::mobile-login[snippets='http-request,request-headers,curl-request,http-response,response-fields']


== 刷新Token

=== Web端用户刷新Token

A `POST` request is used to a new web refresh token （Web 用户刷新Token）

operation::web-refresh-token[snippets='http-request,request-headers,curl-request,http-response,response-fields']

=== 移动端用户刷新Token

A `POST` request is used to a new mobile refresh token (移动端用户刷新Token)

operation::mobile-refresh-token[snippets='http-request,request-headers,curl-request,http-response,response-fields']