spring:
  application:
    name: bs-ops-sys
  profiles:
    active: dev
  cloud:
    alibaba:
      seata:
        tx-service-group: b2b_fs_tx_group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      default-transaction-isolation: 2
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: dev
  cloud:
    config:
      uri: http://192.168.63.195:9888